source 'https://github.com/CocoaPods/Specs.git'

target 'VPInternationalization', :exclusive => true do
  pod "VPInternationalization", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "VPInternationalization", :path => "../"

  
end
